"""initial migration

Revision ID: 18ee27de3fec
Revises: 
Create Date: 2026-06-22 22:30:14.936857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18ee27de3fec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_user',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.Enum('kabag_operasional', 'manager'), nullable=False),
    sa.PrimaryKeyConstraint('id_user'),
    sa.UniqueConstraint('username')
    )
    op.create_table('tbl_distribusi',
    sa.Column('id_distribusi', sa.Integer(), nullable=False),
    sa.Column('periode_tanggal', sa.Date(), nullable=False),
    sa.Column('jumlah_distribusi', sa.Float(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['tbl_user.id_user'], ),
    sa.PrimaryKeyConstraint('id_distribusi'),
    sa.UniqueConstraint('periode_tanggal')
    )
    op.create_table('tbl_evaluasi_model',
    sa.Column('id_evaluasi', sa.Integer(), nullable=False),
    sa.Column('tanggal_evaluasi', sa.DateTime(), nullable=True),
    sa.Column('mae_sarima', sa.Float(), nullable=True),
    sa.Column('rmse_sarima', sa.Float(), nullable=True),
    sa.Column('mape_sarima', sa.Float(), nullable=True),
    sa.Column('mae_hw', sa.Float(), nullable=True),
    sa.Column('rmse_hw', sa.Float(), nullable=True),
    sa.Column('mape_hw', sa.Float(), nullable=True),
    sa.Column('model_terbaik', sa.String(length=20), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['tbl_user.id_user'], ),
    sa.PrimaryKeyConstraint('id_evaluasi')
    )
    op.create_table('tbl_peramalan',
    sa.Column('id_peramalan', sa.Integer(), nullable=False),
    sa.Column('id_evaluasi', sa.Integer(), nullable=True),
    sa.Column('periode_prediksi', sa.Date(), nullable=False),
    sa.Column('nilai_prediksi_sarima', sa.Float(), nullable=True),
    sa.Column('nilai_prediksi_hw', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id_evaluasi'], ['tbl_evaluasi_model.id_evaluasi'], ),
    sa.PrimaryKeyConstraint('id_peramalan')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_peramalan')
    op.drop_table('tbl_evaluasi_model')
    op.drop_table('tbl_distribusi')
    op.drop_table('tbl_user')
    # ### end Alembic commands ###
