"""change jumlah_distribusi to Integer

Revision ID: 484b57f71f52
Revises: 651c658225b5
Create Date: 2026-07-20 23:04:34.857617

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '484b57f71f52'
down_revision = '651c658225b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_distribusi', schema=None) as batch_op:
        batch_op.alter_column('jumlah_distribusi',
               existing_type=mysql.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_distribusi', schema=None) as batch_op:
        batch_op.alter_column('jumlah_distribusi',
               existing_type=sa.Integer(),
               type_=mysql.FLOAT(),
               existing_nullable=False)

    # ### end Alembic commands ###
